name: Build, Push & Remote Deploy

on:
  push:
    branches: [dev]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Docker Hub login
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 2️⃣ Build immagine
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/python_template_image
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_HASH .

      # 3️⃣ Push su registry
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/python_template_image
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_HASH

      # 4️⃣ Deploy remoto via SSH
      - name: Remote Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop python_template_container || true
            docker rm python_template_container || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/python_template_image:latest
            docker run -d -p 4000:4000 --name python_template_container ${{ secrets.DOCKER_USERNAME }}/python_template_image:latest
