name: Build and Run Docker on Mac

on:
  push:
    branches: [dev]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python_template .

      - name: Stop old container if exists
        run: |
          docker stop python_template_container || true
          docker rm python_template_container || true

      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name python_template_container python_template

      - name: Test the API
        run: curl http://localhost:4000/hello
